### ISSUE TITLE
Offboard control using mavros setpoint attitude

### ISSUE THREAD

**Issue by mouhyemen** [PegasusSimulator/PegasusSimulator#7]
Hi Marcelo,
I wanted to double check on this point. I am interested in controlling the drone using mavros in offboard mode and simulating it in isaac sim. Specifically, using attitude body rate setpoints and thrust.

The mavlink backend should be able to handle this right? It will make sure that the attitude setpoints sent via mavlink are tracked by px4 sitl, which in return will send the actuator controls for the rotors simulated in isaac sim.

Secondly, I noticed the mavlink backend sends ground truth information (but not position). I am wondering if that can have an impact on doing attitude setpoint control.

**Comment by MarceloJacinto** [comment]
Sorry for the huge delay on the reply. Maybe this is coming a bit late, but:

1) The mavlink backend pipeline looks like this:

The mavlink_backend (receives control to the individual thrusters from px4, and sends the simulated sensor data to px4). The groundtruth part here is not critical. 

Then px4 uses the simulated sensor data and fuses it with the filter, so that it can be used by the control loops. The control loops inside PX4 will compute the desired rotor velocities based on the attitude body rate setpoints and thrust. This section is independent from Pegasus and is done by PX4 directly. 

Since the simulation is running in lockstep like PX4, I don’t see a reason why it would not work, but let me know if you have troubles!
